apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
        member: consul-1
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: consul
          image: "consul:0.7.2"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          args:
            - "agent"
            - "-ui"
            - "-node=consul-1"
            - "-data-dir=/var/lib/consul"
            - "-server"
            - "-bootstrap-expect=3"
            - "-advertise=$(CONSUL_1_SERVICE_HOST)"
            - "-rejoin"
            - "-client=0.0.0.0"
            - "-config-dir=/etc/consul"
          ports:
            - containerPort: 8300
              name: server
            - containerPort: 8301
              protocol: "TCP"
              name: serflan-tcp
            - containerPort: 8301
              protocol: "UDP"
              name: serflan-udp
            - containerPort: 8302
              protocol: "TCP"
              name: serfwan-tcp
            - containerPort: 8302
              protocol: "UDP"
              name: serfwan-udp
            - containerPort: 8400
              name: rpc-port
            - containerPort: 8500
              name: api-port
            - containerPort: 8600
              protocol: "TCP"
              name: consuldns-tcp
            - containerPort: 8600
              protocol: "UDP"
              name: consuldns-udp
          volumeMounts:
            - mountPath: /var/lib/consul
              name: consol-1-pvc
            - name: "consulconfig"
              mountPath: /etc/consul

      volumes:
        - persistentVolumeClaim:
          claimName: consol-1-pvc
        - name: "consulconfig"
          "secret": {
            "secretName": "consul-config"
          }
