apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consol-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - consul.ncrcloud.pw
    secretName: consol-tls
  rules:
  - host: consul.ncrcloud.pw
    http:
      paths:
      - path: /
        backend:
          serviceName: consol-svc
          servicePort: 80