# Front-end load-balancer service for vault instances
apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  labels:
    app: vault
spec:
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
    name: vaultport
  selector:
    app: vault  
